### ISSUE TITLE
Usernames with "+" are not urlencoded when used to retrieve userroles

### ISSUE THREAD

**Issue by wigahluk** [30x/authsdk#1]
At ln 49 of apigee.go you have:
    url := fmt.Sprintf("https://%s/v1/users/%s/userroles", apiBase, token.GetUsername())

if the use  has a + sign it will not be escaped and interpreted as a space on the URL, resulting in a wrong call.

**Comment by mpnally** [comment]
Interesting. "+" is a valid character in a path segment–it should not normally be necessary to escape it. Which piece of software is interpreting + as space?

**Comment by wigahluk** [comment]
the result of token.GetUsername() can be something like `a+a@a.com` and the resulting url will become: 

```
https://{domain}/v1/users/a+a@a.com/userroles
```

which if not escaped, will cause the backend to parse the username as `a a@a.com`, an invalid user name and also not the same as the original one: `a+a@a.com`.

**Comment by mpnally** [comment]
Shouldn't this be fixed in the misbehaving backend, rather than by making
client escape the '+'? Which is the offending backend? Or perhaps I am wrong and '+' is illegal—which spec says so?

**Comment by wigahluk** [comment]
It is the Apigee Public API. You are right, it should be not an issue to include a `+` sign in the url. I will create a ticket for Apigee Public API.

Does it makes sense to also escape the `+` character in this tool? (given that it is designed to be used with Apigee APIs)

**Comment by mpnally** [comment]
I think it makes sense to escape the '+' as a work-around. We can also open an issue to take it back out again when the root problem is fixed in the backend.

**Comment by tnine** [comment]
I've just tested this, even encoding it doesn't work.  Are we sure this isn't an issue with the api endpoint?

This fails, though it's correct to http spec

`https://api.e2e.apigee.net/v1/users/tnine+plus@apigee.com/userroles/`

This fails as well
`https://api.e2e.apigee.net/v1/users/tnine%2Bplus@apigee.com/userroles/`

This endpoint doesn't work in either scenario, even with a valid SSO JWT token.  I'm not sure this is something I have the ability to fix.

**Comment by wigahluk** [comment]
How are you doing the call?

If I use curl both work:

```
curl -X GET
-H "Authorization: Basic ***"
"https://api.e2e.apigee.net/v1/users/tnine+plus@apigee.com/userroles/"
```

and 

```
curl -X GET
-H "Authorization: Basic ***"
"https://api.e2e.apigee.net/v1/users/tnine%2Bplus@apigee.com/userroles/"
```

My guess is that there is an issue with the encoding of the call in your client library.

Using Postman works too.

**Comment by tnine** [comment]
@wigahluk wigahluk

I wasn't able to get this to work with a valid JWT token.  I make the following.

`curl -X GET
-H "Authorization: Bearer <JWT TOKEN> "
"https://api.e2e.apigee.net/v1/users/tnine+plus@apigee.com/userroles/"`

`curl -X GET
-H "Authorization: Bearer <JWT TOKEN> "
"https://api.e2e.apigee.net/v1/users/tnine%2Bplus@apigee.com/userroles/"`

Neither work, I receive a 403 for both.  Note that this IS with postman.  I wanted to test it manually before implementing this.

**Comment by wigahluk** [comment]
I can confirm the issue. It is failing if I use a user with a + sign against the API using JWT tokens. This doesn't seems to be an issue with authsdk but with the JWT handling on Apigee API.

**Comment by tnine** [comment]
Ok, I've rolled back the code to it's previous state.  We can re-visit once the API is corrected.  Current production worthy sha is 50e1bb8adac0afdac021b4b08091876d1a70324c

**Comment by mpnally** [comment]
It didn't work for me either. I believe that this is because the code is using the wrong URL. The code is using `https://api.enterprise.apigee.com/v1/users/{user_email}/userroles`. It appears that you have to have special privileges to access that resource. If instead we use `https://api.enterprise.apigee.com/v1/organizations/{org_name}/userroles` then it will work—that resource is accessible by all users. There is also `https://api.enterprise.apigee.com/v1/organizations/{org_name}/userroles/orgadmin/users/{user_email}` which seems to work for me.

**Comment by wigahluk** [comment]
I have made the same call with users with no "+" sign in the name and the call works as expected. It only fails if the user has a "+" sign.

**Comment by mpnally** [comment]
Are you sure that there were not other differences? For example, the user without the `+` has sysadmin privileges, while the user with the `+` does not? Or some other privilege difference?

**Comment by wigahluk** [comment]
I tried with two org-admins, one with a + sign and one without, none of them sysadmin uses. The call works with the user that has no + sign

**Comment by mpnally** [comment]
Very mysterious. We'll need to get the Edge (or SSO) guys to take a look. In the mean time, we can use the alternative URLs as a work-around.
